import { Inter } from "next/font/google";
import "./globals.css";
import StarBgCanvas from "@/components/StarBg";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={`${inter.className} overflow-y-scroll overflow-x-hidden bg-[#030014]`}>
                <StarBgCanvas />
                <Navbar />
                {children}
            </body>
        </html>
    );
}
